### ISSUE TITLE
Changes to document

### ISSUE THREAD

**Issue by icambron** [moment/momentjs.com#69]
Breaking changes
- [x] `isValid()` returns `true` for dates that get moved by DSTs ( #1140)
- [x] `format()` returns 'Invalid date' for invalid dates - (#1140)
- [ ] ~~`toString()` always returns the string in English (#1111)~~ We don't seem to document this at all.
- [x] Renamed `moment+langs.js` to `moment-with-langs.js` (#1138)

New features
- [x] `parsingFlags()` (#1140)
- [x] `isDSTShifted()` (#1140)
- [x] New parsing formats - w, ww, W, WW, e, E, d, dd, ddd, dddd (#1141)
- [x] New languages: Bosnian (#1144), Uzbek (#1129), Aussi English (#1126)
- [x] `parseZone()` (#1106)
- [x] `invalidMoment()` (#1098)
- [x] listing functions: `months`, `shortMonths`, `weekdays`, `weekdaysShort`, `weekdaysMin` (#1097)
- [x] Allow `noGlobal` with AMD (#1089)
- [x] `normalizeUnits()` (#1074)
- [x] .NET-style duration parser now accepts times without seconds (#1059)
- [x] Strict parsing (#913)

Enhancements
- [ ] ~~Updates to Bulgarian (#1149), Hungarian (#1137), Dutch (#1093)~~ Release notes only
- [ ] ~~Languages now export themselves. (#1147)~~ Probably unnecessary to document.
- [x] Selecting a language returns the language identifier (#1142)
- [x] Can select from an array of languages (#1142)
- [x] Language selection substrings of the language identifier (#1142)
- [x] Use heuristics for choosing between array formats (#1094)
- [x] ISO parser accepts weeks and ordinals (#1141)
